# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_log_posterior_Pi_cpp <- function(Pi, beta_vec) {
    .Call(`_tggp4networks_compute_log_posterior_Pi_cpp`, Pi, beta_vec)
}

compute_entropy_Pi_cpp <- function(Pi) {
    .Call(`_tggp4networks_compute_entropy_Pi_cpp`, Pi)
}

rand_communities <- function(K, nodes_i_j_idx, N_i_j_sorted, edges_presplit_order, Pi_i_j) {
    .Call(`_tggp4networks_rand_communities`, K, nodes_i_j_idx, N_i_j_sorted, edges_presplit_order, Pi_i_j)
}

#' Draws `n_samples` random variates from a Dirichlet distribution with
#' `concentrations`= (concentrations[1], ..., concentrations[K])
rand_dirichlet_singleconc <- function(concentrations, n_samples) {
    .Call(`_tggp4networks_rand_dirichlet_singleconc`, concentrations, n_samples)
}

#' Provided with a KxN matrix `concentrations`, draws one random variate from
#' each i of N Dirichlet distributions with concentration parameters
#' (concentrations[1, i], ..., concentrations[K, i])
rand_dirichlet_multiconc <- function(concentrations) {
    .Call(`_tggp4networks_rand_dirichlet_multiconc`, concentrations)
}

update_auxiliary_tables <- function(M_counts, beta_vec, alpha_0) {
    .Call(`_tggp4networks_update_auxiliary_tables`, M_counts, beta_vec, alpha_0)
}

sample_book_keep_concordant <- function(n_ij, Pi_ij, M_counts, rows_obs_edges, cols_obs_edges) {
    .Call(`_tggp4networks_sample_book_keep_concordant`, n_ij, Pi_ij, M_counts, rows_obs_edges, cols_obs_edges)
}

sample_multiple_n_and_p <- function(n_ii, p_ii) {
    .Call(`_tggp4networks_sample_multiple_n_and_p`, n_ii, p_ii)
}

propose_communities <- function(nodes_i_j_idx, N_i_j_sorted, edges_presplit_order, Pi) {
    .Call(`_tggp4networks_propose_communities`, nodes_i_j_idx, N_i_j_sorted, edges_presplit_order, Pi)
}

book_keep_selected_edges <- function(M_counts, nodes_i_j_selected, kappas_selected) {
    .Call(`_tggp4networks_book_keep_selected_edges`, M_counts, nodes_i_j_selected, kappas_selected)
}

prepare_R_obs <- function(N_nobs, N, w_obs, Pi_obs, Pi_nobs) {
    .Call(`_tggp4networks_prepare_R_obs`, N_nobs, N, w_obs, Pi_obs, Pi_nobs)
}

prepare_R_unobs <- function(N_nobs, w_nobs, Pi_nobs) {
    .Call(`_tggp4networks_prepare_R_unobs`, N_nobs, w_nobs, Pi_nobs)
}

sample_unobs_nodes_edges <- function(N_tot, N_nobs, K, tot_R, joined_network, R_obs_unobs, Pi_all, M_counts) {
    .Call(`_tggp4networks_sample_unobs_nodes_edges`, N_tot, N_nobs, K, tot_R, joined_network, R_obs_unobs, Pi_all, M_counts)
}

book_keep_edges_counts_ggp <- function(N_ij, rows_obs_edges, cols_obs_edges, N_counts) {
    .Call(`_tggp4networks_book_keep_edges_counts_ggp`, N_ij, rows_obs_edges, cols_obs_edges, N_counts)
}

